# Generated by Django 3.2.3 on 2021-07-09 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_event_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='event',
            name='topLayer',
        ),
    ]
