# Generated by Django 3.2.3 on 2022-02-25 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_client_webmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webmessage',
            old_name='client',
            new_name='clientName',
        ),
    ]
