# Generated by Django 3.2.3 on 2022-03-10 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_rename_client_webmessage_clientname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webmessage',
            name='clientName',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='WebMessage',
        ),
    ]
