# Generated by Django 3.2.3 on 2022-03-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('imageBG', models.ImageField(blank=True, null=True, upload_to='images/link_page')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/link_page')),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
